### ISSUE TITLE
download packages each time

### ISSUE THREAD

**Issue by honarkhah** [softasap/sa-prometheus-exporters#6]
I think we should add some condition to check if exporter already exists!

**Comment by Voronenko** [comment]
Agree.  Let's come with reasonable pattern for check

**Comment by honarkhah** [comment]
I think we could just check the file stats, if already exist we can skip other tasks

**Comment by honarkhah** [comment]
https://github.com/softasap/sa-prometheus-exporters/pull/9

**Comment by Voronenko** [comment]
There was issue in apache exporter preventing second run from succeed.
I have also updated syntax according linting rules - so please rebase over master on next PR if any.

Thanks for improvement!

**Comment by honarkhah** [comment]
Thanks
